### ISSUE TITLE
JSON 入出力部分の実装

### ISSUE THREAD

**Issue by hata6502** [blue-hood/SynthCore#2]

**Comment by kuromike0629** [comment]
ライブラリを使う実装は可能ですか？
それともJSONパーサは内部で持っているべき？

**Comment by hata6502** [comment]
C++ では cereal というライブラリを使っています。
このライブラリのおかげで簡単に JSON 読み書きできますが、
それでも静的型付けな C++ の言語仕様との相性は悪いですね。
http://uscilab.github.io/cereal/index.html

**Comment by hata6502** [comment]
#4 に統合します。
