### ISSUE TITLE
SynthShell の仮実装

### ISSUE THREAD

**Issue by hata6502** [blue-hood/SynthCore#3]
main() を SynthShell に持たせる。
STDIN から JSON を読み込んでそのまま Core に投げる。
Core からのレスポンスをそのまま STDOUT に投げる。

イメージ
```
int main(){
    while(1){
        string request = gets();
        string response = SynthCore::send(request);
        cout << response << endl;
    }
}
```

**Comment by kuromike0629** [comment]
コアの内部は基本的にはコマンドの入力に対して同期か非同期でしょうか？

**Comment by hata6502** [comment]
同期/非同期というより、ポーリング式かな。
例えば play コマンドは半永久的に処理が続くから、
処理の区切り目で DoEvents() 的なのを呼び出してメッセージ処理させるかも。
