### ISSUE TITLE
SynrhCore と SynthShell で名前空間を分ける

### ISSUE THREAD

**Issue by hata6502** [blue-hood/SynthCore#4]

**Comment by kuromike0629** [comment]
密結合すぎるのであれば完全に分離して、SynthCoreはデーモン扱いにするのも良いと思います。

**Comment by hata6502** [comment]
確かに、デーモン化アリだと思います。SynthCoreはC++で作るけど、Shellはphpやnode.jsで作ったほうが簡単ですね。

**Comment by hata6502** [comment]
うーん、デーモン化はやりすぎなような。
http://php.net/manual/ja/function.proc-close.php単純なプロセス間通信はどうでしょうか？

**Comment by hata6502** [comment]
http://php.net/manual/ja/function.popen.php

**Comment by hata6502** [comment]
PHP で単純なプロセス間通信。
標準入出力でパイプ。
https://github.com/blue-hood/SynthCore/tree/%234
